apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-logs-folder
  namespace: airflow
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: airflow
     name: airflow-local-logs-folder
  hostPath:
    path: "/home/romain/Documents/association/demaretu/src/provider/logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-logs-folder
  namespace: airflow
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi